### ISSUE TITLE
这个库是如何编译出来的？

### ISSUE THREAD

**Issue by 5hito** [octree/ClockHandRotationKit#2]
这个是通过源码来编译出来的吗？有没有源码提供？

**Comment by 5hito** [comment]
小组件如何实现平移动画

**Comment by octree** [comment]
https://github.com/orgs/TopWidgets/repositories

**Comment by octree** [comment]
https://github.com/TopWidgets/SwingAnimation

**Comment by octree** [comment]
已经开源了

**Comment by 5hito** [comment]
我还是不太懂ClockHandRotationKit是怎么来的，我看了下你提供的swinganimation是基于ClockHandRotationKit来使用的，但是对于ClockHandRotationKit是怎么来，我挺好奇的。方便说说吗？

**Comment by octree** [comment]
下载 Xcode 13.3 打包的

**Comment by 5hito** [comment]
能不能说明下具体哪些api，因为我也用13.3去找，没找到对应的。你截图或者简单说明下吗？

**Comment by 5hito** [comment]
我知道有这个api：_clockHandRotationEffect，是直接利用这个api打包出来吗？但是这个在新xcode就编译不过

**Comment by octree** [comment]
你自己写一个 Modifier 包一下这个 API，然后打包成 `XCFramework`

**Comment by 5hito** [comment]
那就是只用到这个_clockHandRotationEffect，没有其他的api吧？

**Comment by octree** [comment]
Yeah

**Comment by 5hito** [comment]
非常感谢。你是在哪里，看下有没有机会请你吃个饭？

**Comment by octree** [comment]
客气了，成都的，一个城市的概率不大 😂

**Comment by 5hito** [comment]
😄以后有去成都请你。

**Comment by 5hito** [comment]
在咨询下，我用xcode13编译的库，xcode14报这个问题，是哪里没有设置好吗？
错误：Module compiled with Swift 5.6.1 cannot be imported by the Swift 5.7.2 compiler

**Comment by yeatse** [comment]
> 在咨询下，我用xcode13编译的库，xcode14报这个问题，是哪里没有设置好吗？
> 错误：Module compiled with Swift 5.6.1 cannot be imported by the Swift 5.7.2 compiler

https://stackoverflow.com/a/58656323
